include:
  - project: univention/customers/dataport/upx/common-ci
    file:
      - defaults/stages.yaml
      - defaults/souvap-workflow.yaml
      - templates/souvap.yaml
      - templates/kaniko.yaml
      - jobs/lint-pre-commit.yaml
      - jobs/package-and-publish-helm-charts.yaml


variables:
  SOUVAP_API_V4_URL: https://gitlab.souvap-univention.de/api/v4
  SOUVAP_DOCKER_ACCESS_USER: gitlab-ci-knut
  SOUVAP_HELM_ACCESS_USER: gitlab-ci-knut
  SOUVAP_HELM_PROJECT_ID: 121
  SOUVAP_REGISTRY_HOST: registry.souvap-univention.de
  SOUVAP_REGISTRY_PATH: souvap/tooling/images/univention-store-dav
  SOUVAP_REGISTRY_REPO: ${SOUVAP_REGISTRY_HOST}/${SOUVAP_REGISTRY_PATH}


lint-pre-commit:
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami


build-store-dav:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "docker/store-dav"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/store-dav"


build-config-htpasswd:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "docker/config-htpasswd"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/config-htpasswd"


publish-image-souvap-store-dav:
  needs:
    - job: build-store-dav
  extends: .push-image-souvap
  variables:
    SOUVAP_IMAGE_NAME: "store-dav"


publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap
