---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.9.8"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "templates/souvap.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build.yaml"
      - "jobs/package-and-publish-helm-charts.yaml"

lint-pre-commit:
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "store-dav"
      - "config-htpasswd"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

publish-images:
  extends: .push-image-souvap
  needs:
    - job: container-build
      artifacts: true
      parallel:
        matrix: *build-matrix

publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap
...
