---

services:
  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  store-dav:
    build:
      context: docker/store-dav
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: htpasswd
        target: /etc/nginx/conf/htpasswd
      - type: volume
        source: store-dav-data
        target: /data

volumes:
  pre-commit-cache:
  store-dav-data:

...
