version: "3.9"

name: "dev-local"

services:
  store-dav:
    build:
      context: .
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: htpasswd
        target: /etc/nginx/conf/htpasswd
      - type: volume
        source: store-dav-data
        target: /data
    networks:
      default:
        aliases:
          - store-dav

volumes:
  store-dav-data:
