version: "3.9"

services:
  store-dav:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: store-dav-data
        target: /data


volumes:
  store-dav-data:
