---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ENVIRONMENT: "{{ .Values.storeDav.environment }}"

...
