# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  htpasswd: {{ .Values.storeDav.authHtpasswd | b64enc | quote }}
  users: {{ .Values.storeDav.auth.basicAuth | toYaml | b64enc | quote }}
